import { NavBar } from "@/client/ui/parts/NavBar";
import "./globals.css";
import { TrpcProvider } from "@/utils/trpc-provider";
import { User } from "@prisma/client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function auth() {
  const res = await fetch("http://localhost:3001/api/login");
  // The return value is *not* serialized
  // You can return Date, Map, Set, etc.

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // layout.tsxはAPIでfetchできる
  // このfetchはSSR時に実行される
  // ここでログインユーザーを取得しておくと、Navbarなどでログインユーザーの情報を表示できる
  const res = await auth();
  const user: User = res.user;
  return (
    <html lang="en">
      <body>
        <NavBar user={user} />
        <TrpcProvider>{children}</TrpcProvider>
      </body>
    </html>
  );
}
